DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: false
DATASETS:
  TRAIN: ("pcb_data_train",)
  TEST: ("pcb_data_test",)
MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
  PIXEL_MEAN: [39.94, 50.83, 38.44]
  PIXEL_STD: [42.74, 47.05, 47.55]
  RETINANET:
    NUM_CLASSES: 4
  ROI_HEADS:
    NUM_CLASSES: 4
SOLVER:
  BASE_LR: 0.002
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.25
  IMS_PER_BATCH: 64
  MAX_ITER: 30000
  STEPS: (3600, 7200, 10800, 14400, 18000, 24000)
INPUT:
  MIN_SIZE_TRAIN: (512, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ROTATION_ANGLES: [0, 90, 180, 270]
VERSION: 2
